Feat#4  카카오 로그인 및 Access, Refresh 토큰 발급
TheUpperPart/leaguehub-backend pull request #13
Opened 2023-06-23 03:38 UTC by hennible0612

## 🙆‍♂️ Issue

#4 

## 📝 Description

클라이언트에서 카카오코드를 받은 후 유효하다면 카카오 엑세스 토큰을 받는다.
엑세스 토큰을 사용하여 사용자 정보를 받아온 후 회원가입/로그인을 수행한다.
회원가입/로그인 완료 후 Access, Refresh Token을 발급한다.

테스트 코드는 시큐리티필터와 함께 추가할 예정입니다.

## ✨ Feature

#4 이슈를 참고해주세요

## 👌 Review Change

리뷰를 통해 수정한 부분을 나열해주세요.
This closes #4

2023-06-24 08:27 UTC, HyeonJun0530 requested changes
간단하게 코드 작동 로직보단 의문을 가지게 되는 부분만 리뷰 했어요. 혹시 제가 코멘트에 단 부분에서 이유가 있어서 한 부분이 있다면 적어주시면 감사해요 !

2023-06-24 08:27 UTC, HyeonJun0530 commented on src/main/java/leaguehub/leaguehubbackend/controller/JwtController.java
> +    private JwtService jwtService;
private final을 붙이고 @Autowired를 빼시는게 좋을거 같아요. 필드 주입(@Autowired)은 순환 참조로 인한 오류의 캐치가 런타임 시점에서 잡기 어렵고, 객체의 불변성(final 키워드)를 보장해주지 않기 때문에 생성자로 주입하시면 좋을 것 같아요! @RequiredArgConstructor도 final 키워드가 붙은 필드를 생성자로 만들어주기 때문에 @Autowired 지우시고 final을 붙이면 될 것 같아요 !

생성자 주입 vs 필드 주입에 관한 내용: https://jackjeong.tistory.com/entry/Spring-%EC%83%9D%EC%84%B1%EC%9E%90-%EC%A3%BC%EC%9E%85-vs-%ED%95%84%EB%93%9C-%EC%A3%BC%EC%9E%85-Autowired
@RequiredArgsConstructor에 관한 내용 : https://velog.io/@developerjun0615/Spring-RequiredArgsConstructor-%EC%96%B4%EB%85%B8%ED%85%8C%EC%9D%B4%EC%85%98%EC%9D%84-%EC%82%AC%EC%9A%A9%ED%95%9C-%EC%83%9D%EC%84%B1%EC%9E%90-%EC%A3%BC%EC%9E%85
위의 블로그 내용을 참고 해주시면 될 것 같아요.

2023-06-24 08:27 UTC, HyeonJun0530 commented on src/main/java/leaguehub/leaguehubbackend/controller/JwtController.java
> +    @GetMapping("/reissue/token")
매핑 정보 맨 앞에 /api를 앞에 붙이시면 좋을 것 같아요. @RequestMapping 어노테이션을 이용해서 전부 "/api"를 붙여주세요 !

2023-06-24 08:27 UTC, HyeonJun0530 commented on src/main/java/leaguehub/leaguehubbackend/dto/kakao/KakaoTokenRequestDto.java
> +    }
생성자를 롬복으로 하지 않으신 이유가 있으실까요?

2023-06-24 08:27 UTC, HyeonJun0530 commented on src/main/java/leaguehub/leaguehubbackend/dto/kakao/KakaoTokenResponseDto.java
> +@NoArgsConstructor
롬복 어노테이션 
`@Data `로 생성하시는 것도 나쁘지 않을 것 같아요 !

2023-06-24 08:27 UTC, HyeonJun0530 commented on src/main/java/leaguehub/leaguehubbackend/entity/member/Member.java
> +@AllArgsConstructor
이 것을 쓰신 이유를 알 수 있을까요?

2023-06-24 08:27 UTC, HyeonJun0530 commented on src/main/java/leaguehub/leaguehubbackend/service/kakao/KakaoService.java
> +    private WebClient webClient;
여기서도 필드 주입을 바꿔주셔야 할 것 같아요 !

2023-06-24 08:27 UTC, HyeonJun0530 commented on src/main/java/leaguehub/leaguehubbackend/entity/member/Member.java
>  @NoArgsConstructor
제가 적절하게 바꾸지 못했는데 Entity를 같은 계층 밖에서 생성할 수 없게 @NoArgsConstructor(access = AccessLevel.PROTECTED)로 바꾸어 주세요!

2023-06-24 13:35 UTC, hennible0612 commented on src/main/java/leaguehub/leaguehubbackend/dto/kakao/KakaoTokenRequestDto.java
> +    }
그 부분은 제가 놓쳤네요. Lombok을 사용하여 생성자를 자동 생성하도록 하겠습니다.

2023-06-24 13:51 UTC, hennible0612 commented on src/main/java/leaguehub/leaguehubbackend/entity/member/Member.java
> +@AllArgsConstructor
@Builder 사용 이유는 객체 생성 과정의 복잡성을 줄이고 코드의 가독성을 높이고자 사용했습니다. 
또한 추후에 필요한 필드만 선택적으로 사용하여 객체를 생성할 수 있게 끔 하고자 @Builder를 사용했습니다.

2023-06-25 04:12 UTC, HyeonJun0530 commented on src/main/java/leaguehub/leaguehubbackend/entity/member/Member.java
> +@AllArgsConstructor
@AllArgsConstructor는 어디에서 쓰이는 건가요?

2023-06-25 06:19 UTC, hennible0612 commented on src/main/java/leaguehub/leaguehubbackend/entity/member/Member.java
> +@AllArgsConstructor
@Builder 어노테이션을 사용하기 위해 사용했습니다.
아래 글을 참고 했습니다.
https://resilient-923.tistory.com/418

2023-06-25 06:26 UTC, HyeonJun0530 commented on src/main/java/leaguehub/leaguehubbackend/entity/member/Member.java
> +@AllArgsConstructor
아하 좋네요 그럼 저도 빌더를 통한 생성 클래스를 고려해보겠습니다 !

2023-06-25 07:48 UTC, HyeonJun0530 approved these changes

2023-06-26 09:31 UTC, TinyFrogs submitted a review, later dismissed

2023-06-26 09:31 UTC, HyeonJun0530 submitted a review, later dismissed

2023-06-26 10:02 UTC, HyeonJun0530 approved these changes

2023-06-26 10:02 UTC, TinyFrogs approved these changes

2023-06-26 10:03 UTC, merged