Refactor#463: 토큰 추출 방식 헤더에서 쿠키로 변경
TheUpperPart/leaguehub-backend pull request #487
Opened 2024-04-16 07:04 UTC by HyeonJun0530

## 🙆‍♂️ Issue

#463 

## 📝 Description

액세스 토큰 및 리프레쉬 토큰을 쿠키에 저장하고 해당 처리도 쿠키에서 꺼내 처리하도록 만들었어요. STOMP 연결을 위해서 쿠키에 저장된 RefreshToken으로 JSON 바디에 AccessToken을 담아 클라이언트에서 메모리에 저장해 웹소켓 연결도 가능하도록 처리했어요.
그리고 application-prod.properties에 쿠키 httponly나 secure 옵션을 기본 값 true로 바꾸었으니 참고 부탁드릴께요.
자세한 건 아래 레퍼런스를 참고해주세요.
https://velog.io/@iamtaehoon/sagah

nginx 설정 변경을 통해 스웨거 또한 열어 놨으니 참고 부탁드려요 !

## ✨ Feature

1. 로그인 시 토큰 쿠키에 발급
2. 해당 변경으로 인한 웹소켓 연결 시 토큰을 바디에 받는 api 구현

## 👌 Review Change

리뷰를 통해 수정한 부분을 나열해주세요.
This closes #463

2024-04-17 01:16 UTC, TinyFrogs requested changes
해더 -> 쿠키  토큰 저장방식을 변경하면서 생긴 stomp 오류를 해결한 것 같네요
고생하셨어

2024-04-17 01:16 UTC, TinyFrogs commented on src/main/java/leaguehub/leaguehubbackend/domain/member/controller/MemberAuthController.java
> +        Cookie accessCookie = new Cookie(ACCESS_TOKEN, null);
이 부분은 하나의 메서드로 하여 서비스로 뺄 수 있을 것 같아요

2024-04-17 01:16 UTC, TinyFrogs commented on src/main/java/leaguehub/leaguehubbackend/domain/member/controller/MemberAuthController.java
> +    private void setTokenCookies(HttpServletResponse response, LoginMemberResponse loginMemberResponse) {
메서드를 서비스로 빼 가독성을 높이는 건 어떨까요?

2024-04-17 14:33 UTC, hennible0612 commented on src/main/java/leaguehub/leaguehubbackend/domain/member/controller/MemberAuthController.java
> +    private void setTokenCookies(HttpServletResponse response, LoginMemberResponse loginMemberResponse) {
쿠키는 HTTP 응답의 일부로 클라이언트에 전송해서 컨트롤러가 책임지는게 좋을꺼 같아요!

2024-04-17 14:35 UTC, hennible0612 approved these changes
HTTP only 쿠키 탑재 방식을 properties를 활용하는 방법이 있었네요!
수고하셨습니다~

2024-04-18 00:13 UTC, TinyFrogs commented on src/main/java/leaguehub/leaguehubbackend/domain/member/controller/MemberAuthController.java
> +    private void setTokenCookies(HttpServletResponse response, LoginMemberResponse loginMemberResponse) {
확인했어요

2024-04-18 00:13 UTC, TinyFrogs approved these changes

2024-04-18 11:25 UTC, merged